{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Giphi API",
    "description": "Giphi documentation automatically generated by the <b>swagger-autogen</b> module."
  },
  "host": "giphiapi.arcprojects.es",
  "basePath": "/",
  "tags": [
    {
      "name": "User",
      "description": "Endpoints"
    },
    {
      "name": "Gif",
      "description": "Endpoints"
    }
  ],
  "schemes": [
    "https"
  ],
  "securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "api_key",
      "in": "Authorization header"
    }
  },
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/users": {
      "post": {
        "tags": [
          "User"
        ],
        "description": "Endpoint to create a new user",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "user",
            "in": "body",
            "type": "object",
            "required": true,
            "example": {
              "userName": "toni",
              "email": "toni@gmail.es",
              "password": "1234"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "example": {
                "email": "toni@gmail.es",
                "password": "1234"
              }
            }
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/users/auth": {
      "post": {
        "tags": [
          "User"
        ],
        "description": "Endpoint to login",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "credentials",
            "in": "body",
            "type": "object",
            "required": true,
            "example": {
              "email": "toni@gmail.es",
              "password": "1234"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "User logged in successfully",
            "schema": {
              "example": {
                "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzM4NjRmNjkxMDBkNmQ4NTVhNmZiNSIsImlhdCI6MTY4NTI5MzA2NiwiZXhwIjoxNjg1Mzc5NDY2fQ.FpA0SCC-SDoBqlcwcJpVttC8wAn6jWefsuAh6af7LDg",
                "user": {
                  "id": "6473864f69100d6d855a6fb5",
                  "userName": "toni",
                  "email": "toni@gmail.es",
                  "role": "U"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/users/authgoogle": {
      "post": {
        "tags": [
          "User"
        ],
        "description": "Endpoint to login with Google",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "user",
            "type": "object",
            "in": "body",
            "required": true,
            "example": {
              "firstName": "John",
              "email": "doe@example.com"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "User logged in successfully.",
            "schema": {
              "example": {
                "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0NzM4OGY2MGE2ZjdkNjQ5MTQ5NTZmYyIsImlhdCI6MTY4NTI5MzQxNSwiZXhwIjoxNjg1Mzc5ODE1fQ.xYpJi82HAB3WmFoaYVFG2v3NbQo_x0J9dORUnAppyQU",
                "userGoogle": {
                  "_id": "647388f60a6f7d64914956fc",
                  "userName": "John",
                  "email": "doe@example.com",
                  "role": "U",
                  "createdAt": "2023-05-28T17:01:42.362Z",
                  "updatedAt": "2023-05-28T17:01:42.362Z",
                  "__v": 0
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/users/validate": {
      "get": {
        "tags": [
          "User"
        ],
        "description": "Endpoint to validate the user through the navigation token.",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "token",
            "type": "string",
            "required": true,
            "in": "Authorization header"
          }
        ],
        "responses": {
          "200": {
            "description": "User logged in successfully",
            "schema": {
              "example": {
                "id": "6473864f69100d6d855a6fb5",
                "userName": "toni",
                "email": "toni@gmail.es",
                "role": "U"
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/gifs": {
      "get": {
        "tags": [
          "Gif"
        ],
        "description": "Endpoint to get all gifs.",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "schema": {
              "example": [
                [
                  {
                    "_id": "6471117ddbc2b72b20a768fa",
                    "title": "Work Friday GIF by Microsoft Cloud",
                    "type": "image/png",
                    "gif": "http://res.cloudinary.com/dpcvhtfrt/image/upload/v1685131644/gifs/tfpt8umyj3j21oeal5wn.gif",
                    "createdAt": "2023-05-26T20:07:25.253Z",
                    "updatedAt": "2023-05-26T20:07:25.253Z",
                    "__v": 0
                  },
                  {
                    "_id": "6471117ddbc2b72b20a768fd",
                    "title": "Cat Lol GIF",
                    "type": "image/png",
                    "gif": "http://res.cloudinary.com/dpcvhtfrt/image/upload/v1685131645/gifs/kvxsrfen7etybaxqoe0u.gif",
                    "createdAt": "2023-05-26T20:07:25.701Z",
                    "updatedAt": "2023-05-26T20:07:25.701Z",
                    "__v": 0
                  },
                  {
                    "_id": "64711184dbc2b72b20a76902",
                    "title": "Dogs Love GIF by Chippy the Dog",
                    "type": "image/png",
                    "gif": "http://res.cloudinary.com/dpcvhtfrt/image/upload/v1685131651/gifs/bpsjin8qlc3ptba40vnk.gif",
                    "createdAt": "2023-05-26T20:07:32.037Z",
                    "updatedAt": "2023-05-26T20:07:32.037Z",
                    "__v": 0
                  },
                  {
                    "_id": "64711186dbc2b72b20a76906",
                    "title": "Party Friday GIF by VeeFriends",
                    "type": "image/png",
                    "gif": "http://res.cloudinary.com/dpcvhtfrt/image/upload/v1685131653/gifs/xa2xovhuwuvyzz0yvhr9.gif",
                    "createdAt": "2023-05-26T20:07:34.064Z",
                    "updatedAt": "2023-05-26T20:07:34.064Z",
                    "__v": 0
                  },
                  {
                    "_id": "64711186dbc2b72b20a76909",
                    "title": "Pay Me Kim Kardashian GIF by GQ",
                    "type": "image/png",
                    "gif": "http://res.cloudinary.com/dpcvhtfrt/image/upload/v1685131654/gifs/z9spcrt8j2zrmudtfdu1.gif",
                    "createdAt": "2023-05-26T20:07:34.956Z",
                    "updatedAt": "2023-05-26T20:07:34.956Z",
                    "__v": 0
                  }
                ]
              ]
            },
            "description": "Gifs found."
          },
          "500": {
            "description": "Server Failure."
          }
        }
      }
    },
    "/gifs/{userId}": {
      "get": {
        "tags": [
          "Gif"
        ],
        "description": "Get all user gifs",
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "userId",
            "in": "path",
            "type": "string",
            "required": true
          },
          {
            "name": "token",
            "type": "string",
            "required": true,
            "in": "Authorization header"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Gif"
            }
          },
          "498": {
            "description": "Access Denied"
          }
        }
      }
    },
    "/gifs/{gifId} ": {
      "patch": {
        "tags": [
          "Gif"
        ],
        "description": "Edit gif title",
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "gifId",
            "in": "path",
            "type": "string",
            "required": true
          },
          {
            "name": "token",
            "type": "string",
            "required": true,
            "in": "Authorization header"
          },
          {
            "name": "gifModifyData",
            "type": "object",
            "in": "body",
            "required": true,
            "example": {
              "gifModifyData": {
                "title": "Cat Lol GIF"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "File updated successfully"
          },
          "498": {
            "description": "Access Denied"
          },
          "500": {
            "description": "Failed"
          }
        }
      }
    },
    "/gifs/{gifId}": {
      "delete": {
        "tags": [
          "Gif"
        ],
        "description": "Delete gif",
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "gifId",
            "in": "path",
            "type": "string",
            "required": true
          },
          {
            "name": "token",
            "type": "string",
            "required": true,
            "in": "Authorization header"
          }
        ],
        "responses": {
          "200": {
            "description": "Deleted"
          },
          "498": {
            "description": "Access Denied"
          },
          "500": {
            "description": "File does not exist"
          }
        }
      }
    },
    "/gifs/search/user/{query}": {
      "get": {
        "tags": [
          "Gif"
        ],
        "description": "Search in user gifs section",
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "query",
            "in": "path",
            "type": "string",
            "required": true
          },
          {
            "name": "token",
            "type": "string",
            "required": true,
            "in": "Authorization header"
          }
        ],
        "responses": {
          "200": {
            "description": "User gifs list",
            "schema": {
              "example": [
                {
                  "_id": "6471117ddbc2b72b20a768fa",
                  "title": "Work Friday GIF by Microsoft Cloud",
                  "type": "image/png",
                  "gif": "http://res.cloudinary.com/dpcvhtfrt/image/upload/v1685131644/gifs/tfpt8umyj3j21oeal5wn.gif",
                  "createdAt": "2023-05-26T20:07:25.253Z",
                  "updatedAt": "2023-05-26T20:07:25.253Z",
                  "__v": 0
                },
                {
                  "_id": "6471117ddbc2b72b20a768fd",
                  "title": "Cat Lol GIF",
                  "type": "image/png",
                  "gif": "http://res.cloudinary.com/dpcvhtfrt/image/upload/v1685131645/gifs/kvxsrfen7etybaxqoe0u.gif",
                  "createdAt": "2023-05-26T20:07:25.701Z",
                  "updatedAt": "2023-05-26T20:07:25.701Z",
                  "__v": 0
                },
                {
                  "_id": "64711184dbc2b72b20a76902",
                  "title": "Dogs Love GIF by Chippy the Dog",
                  "type": "image/png",
                  "gif": "http://res.cloudinary.com/dpcvhtfrt/image/upload/v1685131651/gifs/bpsjin8qlc3ptba40vnk.gif",
                  "createdAt": "2023-05-26T20:07:32.037Z",
                  "updatedAt": "2023-05-26T20:07:32.037Z",
                  "__v": 0
                },
                {
                  "_id": "64711186dbc2b72b20a76906",
                  "title": "Party Friday GIF by VeeFriends",
                  "type": "image/png",
                  "gif": "http://res.cloudinary.com/dpcvhtfrt/image/upload/v1685131653/gifs/xa2xovhuwuvyzz0yvhr9.gif",
                  "createdAt": "2023-05-26T20:07:34.064Z",
                  "updatedAt": "2023-05-26T20:07:34.064Z",
                  "__v": 0
                },
                {
                  "_id": "64711186dbc2b72b20a76909",
                  "title": "Pay Me Kim Kardashian GIF by GQ",
                  "type": "image/png",
                  "gif": "http://res.cloudinary.com/dpcvhtfrt/image/upload/v1685131654/gifs/z9spcrt8j2zrmudtfdu1.gif",
                  "createdAt": "2023-05-26T20:07:34.956Z",
                  "updatedAt": "2023-05-26T20:07:34.956Z",
                  "__v": 0
                }
              ]
            }
          },
          "498": {
            "description": "Access Denied"
          }
        }
      }
    },
    "/gifs/search/users/{query}": {
      "get": {
        "tags": [
          "Gif"
        ],
        "description": "Search all other users gifs by title",
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "query",
            "in": "path",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Other users gifs list",
              "schema": {
                "example": [
                  {
                    "_id": "6471117ddbc2b72b20a768fa",
                    "title": "Work Friday GIF by Microsoft Cloud",
                    "type": "image/png",
                    "gif": "http://res.cloudinary.com/dpcvhtfrt/image/upload/v1685131644/gifs/tfpt8umyj3j21oeal5wn.gif",
                    "createdAt": "2023-05-26T20:07:25.253Z",
                    "updatedAt": "2023-05-26T20:07:25.253Z",
                    "__v": 0
                  },
                  {
                    "_id": "6471117ddbc2b72b20a768fd",
                    "title": "Cat Lol GIF",
                    "type": "image/png",
                    "gif": "http://res.cloudinary.com/dpcvhtfrt/image/upload/v1685131645/gifs/kvxsrfen7etybaxqoe0u.gif",
                    "createdAt": "2023-05-26T20:07:25.701Z",
                    "updatedAt": "2023-05-26T20:07:25.701Z",
                    "__v": 0
                  },
                  {
                    "_id": "64711184dbc2b72b20a76902",
                    "title": "Dogs Love GIF by Chippy the Dog",
                    "type": "image/png",
                    "gif": "http://res.cloudinary.com/dpcvhtfrt/image/upload/v1685131651/gifs/bpsjin8qlc3ptba40vnk.gif",
                    "createdAt": "2023-05-26T20:07:32.037Z",
                    "updatedAt": "2023-05-26T20:07:32.037Z",
                    "__v": 0
                  },
                  {
                    "_id": "64711186dbc2b72b20a76906",
                    "title": "Party Friday GIF by VeeFriends",
                    "type": "image/png",
                    "gif": "http://res.cloudinary.com/dpcvhtfrt/image/upload/v1685131653/gifs/xa2xovhuwuvyzz0yvhr9.gif",
                    "createdAt": "2023-05-26T20:07:34.064Z",
                    "updatedAt": "2023-05-26T20:07:34.064Z",
                    "__v": 0
                  },
                  {
                    "_id": "64711186dbc2b72b20a76909",
                    "title": "Pay Me Kim Kardashian GIF by GQ",
                    "type": "image/png",
                    "gif": "http://res.cloudinary.com/dpcvhtfrt/image/upload/v1685131654/gifs/z9spcrt8j2zrmudtfdu1.gif",
                    "createdAt": "2023-05-26T20:07:34.956Z",
                    "updatedAt": "2023-05-26T20:07:34.956Z",
                    "__v": 0
                  }
                ]
              }
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/gifs/search/all/{query}": {
      "get": {
        "tags": [
          "Gif"
        ],
        "description": "Search all gifs by title",
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "query",
            "in": "path",
            "type": "string",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "All gifs list",
              "schema": {
                "example": [
                  {
                    "_id": "6471117ddbc2b72b20a768fa",
                    "title": "Work Friday GIF by Microsoft Cloud",
                    "type": "image/png",
                    "gif": "http://res.cloudinary.com/dpcvhtfrt/image/upload/v1685131644/gifs/tfpt8umyj3j21oeal5wn.gif",
                    "createdAt": "2023-05-26T20:07:25.253Z",
                    "updatedAt": "2023-05-26T20:07:25.253Z",
                    "__v": 0
                  },
                  {
                    "_id": "6471117ddbc2b72b20a768fd",
                    "title": "Cat Lol GIF",
                    "type": "image/png",
                    "gif": "http://res.cloudinary.com/dpcvhtfrt/image/upload/v1685131645/gifs/kvxsrfen7etybaxqoe0u.gif",
                    "createdAt": "2023-05-26T20:07:25.701Z",
                    "updatedAt": "2023-05-26T20:07:25.701Z",
                    "__v": 0
                  },
                  {
                    "_id": "64711184dbc2b72b20a76902",
                    "title": "Dogs Love GIF by Chippy the Dog",
                    "type": "image/png",
                    "gif": "http://res.cloudinary.com/dpcvhtfrt/image/upload/v1685131651/gifs/bpsjin8qlc3ptba40vnk.gif",
                    "createdAt": "2023-05-26T20:07:32.037Z",
                    "updatedAt": "2023-05-26T20:07:32.037Z",
                    "__v": 0
                  },
                  {
                    "_id": "64711186dbc2b72b20a76906",
                    "title": "Party Friday GIF by VeeFriends",
                    "type": "image/png",
                    "gif": "http://res.cloudinary.com/dpcvhtfrt/image/upload/v1685131653/gifs/xa2xovhuwuvyzz0yvhr9.gif",
                    "createdAt": "2023-05-26T20:07:34.064Z",
                    "updatedAt": "2023-05-26T20:07:34.064Z",
                    "__v": 0
                  },
                  {
                    "_id": "64711186dbc2b72b20a76909",
                    "title": "Pay Me Kim Kardashian GIF by GQ",
                    "type": "image/png",
                    "gif": "http://res.cloudinary.com/dpcvhtfrt/image/upload/v1685131654/gifs/z9spcrt8j2zrmudtfdu1.gif",
                    "createdAt": "2023-05-26T20:07:34.956Z",
                    "updatedAt": "2023-05-26T20:07:34.956Z",
                    "__v": 0
                  }
                ]
              }
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    }
  },
  "definitions": {
    "User": {
      "type": "object",
      "properties": {
        "_id": {
          "type": "string",
          "example": "24jg3243rjfd3"
        },
        "userName": {
          "type": "string",
          "example": "Simon Joe"
        },
        "email": {
          "type": "string",
          "example": "simon_joe@mail.com"
        },
        "role": {
          "type": "string",
          "example": "U"
        }
      },
      "xml": {
        "name": "Parents"
      }
    },
    "Gif": {
      "type": "object",
      "properties": {
        "_id": {
          "type": "string",
          "example": "45sdaf436sfd3"
        },
        "title": {
          "type": "string",
          "example": "The first meme!"
        },
        "gif": {
          "type": "string",
          "example": "https://www.iebschool.com/blog/wp-content/uploads/2015/03/hacer-venta.gif"
        },
        "type": {
          "type": "string",
          "example": "image/png"
        }
      },
      "xml": {
        "name": "User"
      }
    }
  }
}